using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using GameLogic;
using UnityEditor;
using UnityEngine;

namespace GameLogic.Editor.Tools.DataBinding
{
    /// <summary>
    /// 自定义数据绑定代码生成器。
    /// </summary>
    /// <remarks>
    /// 该工具只处理普通数据类型到 DataBinding 运行时类型的同步代码，不负责任何 UI 绑定。
    /// </remarks>
    public static class DataBindingGenerator
    {
        public const string DefaultOutputDirectory = "Assets/GameScripts/HotFix/GameLogic/Generated/DataBinding";
        private const string GeneratedHeader = "// Generated by Tools/数据绑定/生成. Do not edit manually.";

        private static readonly Dictionary<Type, string> TypeAliases = new Dictionary<Type, string>
        {
            { typeof(bool), "bool" },
            { typeof(byte), "byte" },
            { typeof(sbyte), "sbyte" },
            { typeof(char), "char" },
            { typeof(decimal), "decimal" },
            { typeof(double), "double" },
            { typeof(float), "float" },
            { typeof(int), "int" },
            { typeof(uint), "uint" },
            { typeof(long), "long" },
            { typeof(ulong), "ulong" },
            { typeof(object), "object" },
            { typeof(short), "short" },
            { typeof(ushort), "ushort" },
            { typeof(string), "string" },
        };

        private static readonly HashSet<string> Keywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        [MenuItem("Tools/数据绑定/生成")]
        public static void Generate()
        {
            GenerateAll(DefaultOutputDirectory);
        }

        /// <summary>
        /// 生成所有带 <see cref="DataBindingModelAttribute"/> 的数据类型。
        /// </summary>
        public static GenerateResult GenerateAll(string outputDirectory = DefaultOutputDirectory, bool refreshAssetDatabase = true)
        {
            outputDirectory = NormalizeAssetPath(outputDirectory);
            Directory.CreateDirectory(outputDirectory);

            List<Type> modelTypes = TypeCache.GetTypesWithAttribute<DataBindingModelAttribute>()
                .Where(type => !type.IsAbstract && !type.ContainsGenericParameters)
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .ToList();

            GenerateResult result = new GenerateResult(outputDirectory, modelTypes.Count);
            foreach (Type modelType in modelTypes)
            {
                GenerateModelResult modelResult = GenerateModel(modelType, outputDirectory);
                result.Add(modelResult);
            }

            if (refreshAssetDatabase)
            {
                AssetDatabase.Refresh();
            }

            Debug.Log($"DataBinding binder generated: {result.GeneratedCount}/{result.ModelCount}, changed: {result.ChangedCount}, skipped: {result.SkippedCount}");
            return result;
        }

        /// <summary>
        /// 收集当前工程中可生成 Binder 的数据类型信息。
        /// </summary>
        public static List<ModelInfo> CollectModelInfos(string outputDirectory = DefaultOutputDirectory)
        {
            outputDirectory = NormalizeAssetPath(outputDirectory);

            List<Type> modelTypes = TypeCache.GetTypesWithAttribute<DataBindingModelAttribute>()
                .Where(type => !type.IsAbstract && !type.ContainsGenericParameters)
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .ToList();

            List<ModelInfo> infos = new List<ModelInfo>(modelTypes.Count);
            foreach (Type modelType in modelTypes)
            {
                List<BindMember> members = GetDataBindMembers(modelType);
                string fileName = $"{SanitizeFileName(modelType.FullName)}Binder.g.cs";
                string outputPath = NormalizeAssetPath(Path.Combine(outputDirectory, fileName));
                infos.Add(new ModelInfo(
                    modelType.FullName,
                    $"{modelType.Name}Binder",
                    members.Count,
                    members.Count(member => member.IsSignal),
                    members.Count(member => member.Format != null),
                    members.Count(member => member.Tolerance.HasValue),
                    outputPath,
                    File.Exists(outputPath)));
            }

            return infos;
        }

        /// <summary>
        /// 清理由本生成器创建的 Binder 文件。
        /// </summary>
        public static int CleanGeneratedFiles(string outputDirectory = DefaultOutputDirectory, bool refreshAssetDatabase = true)
        {
            outputDirectory = NormalizeAssetPath(outputDirectory);
            if (!Directory.Exists(outputDirectory))
            {
                return 0;
            }

            int deletedCount = 0;
            foreach (string filePath in Directory.GetFiles(outputDirectory, "*Binder.g.cs", SearchOption.TopDirectoryOnly))
            {
                string content = File.ReadAllText(filePath, Encoding.UTF8);
                if (!content.Contains(GeneratedHeader))
                {
                    continue;
                }

                File.Delete(filePath);

                string metaPath = $"{filePath}.meta";
                if (File.Exists(metaPath))
                {
                    File.Delete(metaPath);
                }

                deletedCount++;
            }

            if (deletedCount > 0 && refreshAssetDatabase)
            {
                AssetDatabase.Refresh();
            }

            return deletedCount;
        }

        private static GenerateModelResult GenerateModel(Type modelType, string outputDirectory)
        {
            List<BindMember> members = GetDataBindMembers(modelType);
            if (members.Count == 0)
            {
                string message = $"DataBinding model has no public bindable members: {modelType.FullName}";
                Debug.LogWarning(message);
                return GenerateModelResult.Skipped(modelType.FullName, message);
            }

            string code = BuildCode(modelType, members);
            string fileName = $"{SanitizeFileName(modelType.FullName)}Binder.g.cs";
            string filePath = NormalizeAssetPath(Path.Combine(outputDirectory, fileName));

            if (File.Exists(filePath) && File.ReadAllText(filePath, Encoding.UTF8) == code)
            {
                return GenerateModelResult.Generated(modelType.FullName, filePath, false);
            }

            File.WriteAllText(filePath, code, Encoding.UTF8);
            return GenerateModelResult.Generated(modelType.FullName, filePath, true);
        }

        private static List<BindMember> GetDataBindMembers(Type modelType)
        {
            const BindingFlags flags = BindingFlags.Instance | BindingFlags.Public;
            List<BindMember> members = new List<BindMember>();

            foreach (FieldInfo field in modelType.GetFields(flags).OrderBy(member => member.MetadataToken))
            {
                if (field.IsSpecialName || field.GetCustomAttribute<DataBindIgnoreAttribute>() != null)
                {
                    continue;
                }

                AddMember(members, modelType, field.Name, field.FieldType, $"data.{EscapeIdentifier(field.Name)}", field);
            }

            foreach (PropertyInfo property in modelType.GetProperties(flags).OrderBy(member => member.MetadataToken))
            {
                if (property.GetIndexParameters().Length > 0 || property.GetMethod == null ||
                    property.GetCustomAttribute<DataBindIgnoreAttribute>() != null)
                {
                    continue;
                }

                AddMember(members, modelType, property.Name, property.PropertyType, $"data.{EscapeIdentifier(property.Name)}", property);
            }

            return members;
        }

        private static void AddMember(
            ICollection<BindMember> members,
            Type modelType,
            string name,
            Type sourceType,
            string accessExpression,
            MemberInfo memberInfo)
        {
            DataBindSignalAttribute signalAttribute = memberInfo.GetCustomAttribute<DataBindSignalAttribute>();
            DataBindFormatAttribute formatAttribute = memberInfo.GetCustomAttribute<DataBindFormatAttribute>();
            DataBindToleranceAttribute toleranceAttribute = memberInfo.GetCustomAttribute<DataBindToleranceAttribute>();

            if (signalAttribute != null)
            {
                if (sourceType != typeof(bool))
                {
                    Debug.LogWarning($"[DataBindSignal] only supports bool members. Skipped: {modelType.FullName}.{name}");
                    return;
                }

                members.Add(BindMember.Signal(name, accessExpression));
                return;
            }

            Type bindingType = formatAttribute != null ? typeof(string) : sourceType;
            members.Add(new BindMember(name, sourceType, bindingType, accessExpression, formatAttribute?.Format, toleranceAttribute?.Tolerance));
        }

        private static string BuildCode(Type modelType, IReadOnlyList<BindMember> members)
        {
            string namespaceName = string.IsNullOrEmpty(modelType.Namespace) ? null : modelType.Namespace;
            string bindingClassName = $"{modelType.Name}Binder";
            string modelTypeName = GetTypeName(modelType);
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine(GeneratedHeader);
            builder.AppendLine("// This file belongs to custom data binding, not UI binding.");
            builder.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                builder.AppendLine($"namespace {namespaceName}");
                builder.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(namespaceName) ? string.Empty : "    ";
            builder.AppendLine($"{indent}public sealed class {bindingClassName}");
            builder.AppendLine($"{indent}{{");

            foreach (BindMember member in members)
            {
                if (member.IsSignal)
                {
                    builder.AppendLine($"{indent}    public global::GameLogic.DataBindingSignal {EscapeIdentifier(member.Name)} {{ get; }} = new global::GameLogic.DataBindingSignal();");
                }
                else
                {
                    builder.AppendLine($"{indent}    public global::GameLogic.DataBindingProperty<{GetTypeName(member.BindingType)}> {EscapeIdentifier(member.Name)} {{ get; }} = new global::GameLogic.DataBindingProperty<{GetTypeName(member.BindingType)}>();");
                }
            }

            bool hasSignals = members.Any(member => member.IsSignal);
            if (hasSignals)
            {
                builder.AppendLine();
                foreach (BindMember member in members.Where(member => member.IsSignal))
                {
                    builder.AppendLine($"{indent}    private bool {GetSignalStateField(member.Name)};");
                }
            }

            builder.AppendLine();
            builder.AppendLine($"{indent}    public void SyncFrom({modelTypeName} data)");
            builder.AppendLine($"{indent}    {{");
            if (!modelType.IsValueType)
            {
                builder.AppendLine($"{indent}        if (data == null)");
                builder.AppendLine($"{indent}        {{");
                builder.AppendLine($"{indent}            return;");
                builder.AppendLine($"{indent}        }}");
                builder.AppendLine();
            }

            foreach (BindMember member in members)
            {
                AppendSyncLine(builder, indent, member);
            }

            builder.AppendLine($"{indent}    }}");

            builder.AppendLine();
            builder.AppendLine($"{indent}    public void SyncAndFlush({modelTypeName} data)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        SyncFrom(data);");
            builder.AppendLine($"{indent}        Flush();");
            builder.AppendLine($"{indent}    }}");

            builder.AppendLine();
            builder.AppendLine($"{indent}    public void Flush()");
            builder.AppendLine($"{indent}    {{");
            foreach (BindMember member in members.Where(member => !member.IsSignal))
            {
                builder.AppendLine($"{indent}        {EscapeIdentifier(member.Name)}.Flush();");
            }
            builder.AppendLine($"{indent}    }}");

            builder.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        private static void AppendSyncLine(StringBuilder builder, string indent, BindMember member)
        {
            string memberName = EscapeIdentifier(member.Name);

            if (member.IsSignal)
            {
                string stateField = GetSignalStateField(member.Name);
                builder.AppendLine($"{indent}        if ({member.AccessExpression})");
                builder.AppendLine($"{indent}        {{");
                builder.AppendLine($"{indent}            if (!{stateField})");
                builder.AppendLine($"{indent}            {{");
                builder.AppendLine($"{indent}                {memberName}.Emit();");
                builder.AppendLine($"{indent}            }}");
                builder.AppendLine($"{indent}            {stateField} = true;");
                builder.AppendLine($"{indent}        }}");
                builder.AppendLine($"{indent}        else");
                builder.AppendLine($"{indent}        {{");
                builder.AppendLine($"{indent}            {stateField} = false;");
                builder.AppendLine($"{indent}        }}");
                return;
            }

            string valueExpression = member.Format == null
                ? member.AccessExpression
                : $"string.Format(global::System.Globalization.CultureInfo.InvariantCulture, {ToLiteral(member.Format)}, {member.AccessExpression})";

            if (member.Tolerance.HasValue)
            {
                string tolerance = member.Tolerance.Value.ToString("R", CultureInfo.InvariantCulture);
                builder.AppendLine($"{indent}        {memberName}.SetDirty({valueExpression}, (oldValue, newValue) => global::GameLogic.DataBindingComparison.AreEqual(oldValue, newValue, {tolerance}f));");
            }
            else
            {
                builder.AppendLine($"{indent}        {memberName}.SetDirty({valueExpression});");
            }
        }

        private static string GetSignalStateField(string memberName)
        {
            string sanitized = SanitizeIdentifier(memberName);
            if (string.IsNullOrEmpty(sanitized))
            {
                sanitized = "Signal";
            }

            return $"_{char.ToLowerInvariant(sanitized[0])}{sanitized.Substring(1)}SignalActive";
        }

        private static string GetTypeName(Type type)
        {
            if (TypeAliases.TryGetValue(type, out string alias))
            {
                return alias;
            }

            if (type.IsArray)
            {
                return $"{GetTypeName(type.GetElementType())}[]";
            }

            if (type.IsGenericType)
            {
                string genericTypeName = GetNonGenericTypeName(type.GetGenericTypeDefinition());
                string genericArgs = string.Join(", ", type.GetGenericArguments().Select(GetTypeName));
                return $"{genericTypeName}<{genericArgs}>";
            }

            return GetNonGenericTypeName(type);
        }

        private static string GetNonGenericTypeName(Type type)
        {
            string name = type.Name;
            int tickIndex = name.IndexOf('`');
            if (tickIndex >= 0)
            {
                name = name.Substring(0, tickIndex);
            }

            if (type.DeclaringType != null)
            {
                return $"{GetNonGenericTypeName(type.DeclaringType)}.{name}";
            }

            return string.IsNullOrEmpty(type.Namespace) ? name : $"global::{type.Namespace}.{name}";
        }

        private static string EscapeIdentifier(string value)
        {
            return Keywords.Contains(value) ? $"@{value}" : value;
        }

        private static string SanitizeIdentifier(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return string.Empty;
            }

            StringBuilder builder = new StringBuilder(value.Length);
            for (int i = 0; i < value.Length; i++)
            {
                char c = value[i];
                bool valid = i == 0
                    ? char.IsLetter(c) || c == '_'
                    : char.IsLetterOrDigit(c) || c == '_';
                builder.Append(valid ? c : '_');
            }

            return builder.ToString();
        }

        private static string SanitizeFileName(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return "DataBindingModel";
            }

            char[] invalidChars = Path.GetInvalidFileNameChars();
            StringBuilder builder = new StringBuilder(value.Length);
            foreach (char c in value)
            {
                builder.Append(invalidChars.Contains(c) || c == '.' || c == '+' ? '_' : c);
            }

            return builder.ToString();
        }

        private static string NormalizeAssetPath(string path)
        {
            return string.IsNullOrEmpty(path)
                ? DefaultOutputDirectory
                : path.Replace('\\', '/').TrimEnd('/');
        }

        private static string ToLiteral(string value)
        {
            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }

        private sealed class BindMember
        {
            public BindMember(string name, Type sourceType, Type bindingType, string accessExpression, string format, float? tolerance)
            {
                Name = name;
                SourceType = sourceType;
                BindingType = bindingType;
                AccessExpression = accessExpression;
                Format = format;
                Tolerance = tolerance;
            }

            public string Name { get; }

            public Type SourceType { get; }

            public Type BindingType { get; }

            public string AccessExpression { get; }

            public string Format { get; }

            public float? Tolerance { get; }

            public bool IsSignal { get; private set; }

            public static BindMember Signal(string name, string accessExpression)
            {
                return new BindMember(name, typeof(bool), typeof(void), accessExpression, null, null)
                {
                    IsSignal = true
                };
            }
        }

        public sealed class ModelInfo
        {
            public ModelInfo(
                string modelType,
                string binderType,
                int memberCount,
                int signalCount,
                int formattedCount,
                int toleranceCount,
                string outputPath,
                bool generatedFileExists)
            {
                ModelType = modelType;
                BinderType = binderType;
                MemberCount = memberCount;
                SignalCount = signalCount;
                FormattedCount = formattedCount;
                ToleranceCount = toleranceCount;
                OutputPath = outputPath;
                GeneratedFileExists = generatedFileExists;
            }

            public string ModelType { get; }

            public string BinderType { get; }

            public int MemberCount { get; }

            public int SignalCount { get; }

            public int FormattedCount { get; }

            public int ToleranceCount { get; }

            public string OutputPath { get; }

            public bool GeneratedFileExists { get; }
        }

        public sealed class GenerateResult
        {
            private readonly List<GenerateModelResult> _models = new List<GenerateModelResult>();

            public GenerateResult(string outputDirectory, int modelCount)
            {
                OutputDirectory = outputDirectory;
                ModelCount = modelCount;
            }

            public string OutputDirectory { get; }

            public int ModelCount { get; }

            public int GeneratedCount { get; private set; }

            public int ChangedCount { get; private set; }

            public int SkippedCount { get; private set; }

            public IReadOnlyList<GenerateModelResult> Models => _models;

            public void Add(GenerateModelResult result)
            {
                _models.Add(result);

                if (result.IsSkipped)
                {
                    SkippedCount++;
                    return;
                }

                GeneratedCount++;
                if (result.Changed)
                {
                    ChangedCount++;
                }
            }
        }

        public sealed class GenerateModelResult
        {
            private GenerateModelResult(string modelType, string outputPath, bool changed, bool isSkipped, string message)
            {
                ModelType = modelType;
                OutputPath = outputPath;
                Changed = changed;
                IsSkipped = isSkipped;
                Message = message;
            }

            public string ModelType { get; }

            public string OutputPath { get; }

            public bool Changed { get; }

            public bool IsSkipped { get; }

            public string Message { get; }

            public static GenerateModelResult Generated(string modelType, string outputPath, bool changed)
            {
                return new GenerateModelResult(modelType, outputPath, changed, false, string.Empty);
            }

            public static GenerateModelResult Skipped(string modelType, string message)
            {
                return new GenerateModelResult(modelType, string.Empty, false, true, message);
            }
        }
    }
}
