// <auto-generated>
//     由 SceneEnumConfig 生成，请勿手改。生成时间：2026-08-25 21:46:40
//     数据源：SceneEnumConfig.asset；命名空间：GameLogic
// </auto-generated>
using System.CodeDom.Compiler;

namespace GameLogic
{
    /// <summary>
    /// 场景类型枚举：与具体场景资源地址（YooAsset location）一一对应。
    /// 由 SceneEnumConfig 自动生成，新增/删除/改名场景请通过配置工具同步，勿手改。
    /// </summary>
    [GeneratedCode("SceneEnumConfig", "1.0")]
    public enum SceneType
    {
        /// <summary>UI场景｜主UI常驻空场景</summary>
        MainScene = 0,
    }
}
