// <auto-generated>
//     由 SceneEnumConfig 生成，请勿手改。生成时间：2026-08-07 19:58:46
// </auto-generated>
using System.CodeDom.Compiler;

namespace GameLogic
{
    /// <summary>
    /// 场景资源地址常量：与 SceneType 枚举一一对应，由 SceneEnumConfig 自动生成。
    /// 值 = 场景文件名（YooAsset AddressByFileName），场景改名后重新生成会自动跟随。
    /// </summary>
    [GeneratedCode("SceneEnumConfig", "1.0")]
    public static class SceneConstName
    {
        public const string MainSceneName = "MainScene";
    }
}
