// <auto-generated>
//     由 SceneEnumConfig 生成，请勿手改。生成时间：2026-08-25 21:46:40
// </auto-generated>
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace GameLogic
{
    /// <summary>
    /// SceneType -> 中文名映射，由 SceneEnumConfig 自动生成。
    /// 中文名为空时回退为枚举名 nameof(SceneType.XXX)。
    /// </summary>
    [GeneratedCode("SceneEnumConfig", "1.0")]
    public static class SceneTypeDisplayName
    {
        private static readonly Dictionary<SceneType, string> _toChineseName = new Dictionary<SceneType, string>
        {
            { SceneType.MainScene, "UI场景" },
        };

        /// <summary>枚举 -> 中文名；ChineseName 为空时回退 nameof 枚举名。</summary>
        public static string GetChineseName(SceneType type)
            => _toChineseName.TryGetValue(type, out var name) ? name : string.Empty;
    }
}
