// <auto-generated>
//     由 SceneEnumConfig 生成，请勿手改。生成时间：2026-08-07 00:00:00
//     注：本文件为初始版本（仅 MainScene），请通过 SceneEnumConfig.asset 同步并生成以覆盖。
// </auto-generated>
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace GameLogic
{
    /// <summary>
    /// SceneType 与场景资源地址的双向映射，由 SceneEnumConfig 自动生成（替代手写 switch/if）。
    /// 反向查询同时支持资源地址与枚举名两种 key（枚举名用于回放文件名解析）；两者相同时按索引器覆盖，不报错。
    /// </summary>
    [GeneratedCode("SceneEnumConfig", "1.0")]
    public static class SceneTypeMapping
    {
        private static readonly Dictionary<SceneType, string> _toName = new Dictionary<SceneType, string>
        {
            { SceneType.MainScene, SceneConstName.MainSceneName },
        };

        private static readonly Dictionary<string, SceneType> _fromName = new Dictionary<string, SceneType>();

        static SceneTypeMapping()
        {
            // 用索引器赋值：资源地址与枚举名相同时覆盖而非抛重复 key 异常
            _fromName[SceneConstName.MainSceneName] = SceneType.MainScene;
            _fromName[nameof(SceneType.MainScene)] = SceneType.MainScene;
        }

        /// <summary>枚举 -> 资源地址；未匹配返回空串。</summary>
        public static string GetSceneName(SceneType type)
            => _toName.TryGetValue(type, out var name) ? name : string.Empty;

        /// <summary>资源地址或枚举名 -> 枚举；未匹配返回 null。</summary>
        public static SceneType? GetSceneTypeFromName(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            return _fromName.TryGetValue(name, out var type) ? type : (SceneType?)null;
        }
    }
}
