//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	public partial class LoadingUI : UIWindow
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private Image m_imgProgress = null!;
		private TextMeshProUGUI m_tmpShowTips = null!;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			if(m_bindComponent == null)
			{
				Log.Error($"根物体: {gameObject.name} 缺少组件 UIBindComponent, 请检查！！！");
				return;
			}
			m_imgProgress = m_bindComponent.GetComponent<Image>(0);
			m_tmpShowTips = m_bindComponent.GetComponent<TextMeshProUGUI>(1);
		}

		#endregion

		#region 事件

		#endregion
	}
}
