using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace TEngine.SceneTools
{
    /// <summary>
    /// 场景枚举代码生成器：读 <see cref="SceneEnumConfig"/> 生成
    /// SceneType.g.cs / SceneConstName.g.cs / SceneTypeMapping.g.cs。
    /// </summary>
    public static class SceneEnumCodeGenerator
    {
        public static void Generate(SceneEnumConfig config)
        {
            if (config == null)
            {
                Debug.LogError("[场景枚举] 配置为空");
                return;
            }

            string outputFolder = string.IsNullOrEmpty(config.OutputFolder) ? SceneEnumConfig.DefaultOutputFolder : config.OutputFolder;
            if (!AssetDatabase.IsValidFolder(outputFolder))
            {
                EditorUtility.DisplayDialog("生成失败", $"代码输出目录不存在：{outputFolder}", "确定");
                return;
            }

            List<SceneEnumConfig.SceneEntry> activeEntries = config.Scenes
                .Where(e => e.Active && e.SceneAsset != null && !string.IsNullOrEmpty(e.EnumName))
                .ToList();

            // 校验枚举名唯一
            var duplicateGroups = activeEntries.GroupBy(e => e.EnumName).Where(g => g.Count() > 1).ToList();
            if (duplicateGroups.Count > 0)
            {
                EditorUtility.DisplayDialog("生成失败",
                    $"存在重复的枚举名：{string.Join(", ", duplicateGroups.Select(g => g.Key))}", "确定");
                return;
            }

            // 规则1：校验枚举值唯一（防止 _toName 字典初始化器重复 key 抛异常）
            var duplicateValues = activeEntries.GroupBy(e => e.EnumValue).Where(g => g.Count() > 1).ToList();
            if (duplicateValues.Count > 0)
            {
                EditorUtility.DisplayDialog("生成失败",
                    $"存在重复的枚举值：{string.Join(", ", duplicateValues.Select(g => $"{g.Key}（{string.Join("/", g.Select(e => e.EnumName))}）"))}", "确定");
                return;
            }

            // 校验枚举名合法
            SceneEnumConfig.SceneEntry invalid = activeEntries.FirstOrDefault(e => !IsValidEnumName(e.EnumName));
            if (invalid != null)
            {
                EditorUtility.DisplayDialog("生成失败",
                    $"枚举名不合法：{invalid.EnumName}（需为合法 C# 标识符，字母/数字/下划线，且不以数字开头）", "确定");
                return;
            }

            string timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

            WriteFile(Path.Combine(outputFolder, "SceneType.g.cs"), BuildEnumSource(activeEntries, timestamp));
            WriteFile(Path.Combine(outputFolder, "SceneConstName.g.cs"), BuildConstSource(activeEntries, timestamp));
            WriteFile(Path.Combine(outputFolder, "SceneTypeMapping.g.cs"), BuildMappingSource(activeEntries, timestamp));

            AssetDatabase.Refresh();
            Debug.Log($"[场景枚举] 代码生成完成：{activeEntries.Count} 个场景，输出到 {outputFolder}");
        }

        private static string BuildEnumSource(List<SceneEnumConfig.SceneEntry> entries, string timestamp)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     由 SceneEnumConfig 生成，请勿手改。生成时间：{timestamp}");
            sb.AppendLine($"//     数据源：SceneEnumConfig.asset；命名空间：{SceneEnumConfig.CodeNamespace}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.CodeDom.Compiler;");
            sb.AppendLine();
            sb.AppendLine($"namespace {SceneEnumConfig.CodeNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 场景类型枚举：与具体场景资源地址（YooAsset location）一一对应。");
            sb.AppendLine("    /// 由 SceneEnumConfig 自动生成，新增/删除/改名场景请通过配置工具同步，勿手改。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GeneratedCode(\"SceneEnumConfig\", \"1.0\")]");
            sb.AppendLine("    public enum SceneType");
            sb.AppendLine("    {");
            foreach (SceneEnumConfig.SceneEntry e in entries)
            {
                if (!string.IsNullOrEmpty(e.DisplayName))
                {
                    sb.AppendLine($"        /// <summary>{EscapeXml(e.DisplayName)}</summary>");
                }
                sb.AppendLine($"        {e.EnumName} = {e.EnumValue},");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildConstSource(List<SceneEnumConfig.SceneEntry> entries, string timestamp)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     由 SceneEnumConfig 生成，请勿手改。生成时间：{timestamp}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.CodeDom.Compiler;");
            sb.AppendLine();
            sb.AppendLine($"namespace {SceneEnumConfig.CodeNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 场景资源地址常量：与 SceneType 枚举一一对应，由 SceneEnumConfig 自动生成。");
            sb.AppendLine("    /// 值 = 场景文件名（YooAsset AddressByFileName），场景改名后重新生成会自动跟随。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GeneratedCode(\"SceneEnumConfig\", \"1.0\")]");
            sb.AppendLine("    public static class SceneConstName");
            sb.AppendLine("    {");
            foreach (SceneEnumConfig.SceneEntry e in entries)
            {
                sb.AppendLine($"        public const string {e.EnumName}Name = \"{GetSceneAddress(e)}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildMappingSource(List<SceneEnumConfig.SceneEntry> entries, string timestamp)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     由 SceneEnumConfig 生成，请勿手改。生成时间：{timestamp}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.CodeDom.Compiler;");
            sb.AppendLine();
            sb.AppendLine($"namespace {SceneEnumConfig.CodeNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// SceneType 与场景资源地址的双向映射，由 SceneEnumConfig 自动生成（替代手写 switch/if）。");
            sb.AppendLine("    /// 反向查询同时支持资源地址与枚举名两种 key（枚举名用于回放文件名解析）。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GeneratedCode(\"SceneEnumConfig\", \"1.0\")]");
            sb.AppendLine("    public static class SceneTypeMapping");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Dictionary<SceneType, string> _toName = new Dictionary<SceneType, string>");
            sb.AppendLine("        {");
            foreach (SceneEnumConfig.SceneEntry e in entries)
            {
                sb.AppendLine($"            {{ SceneType.{e.EnumName}, SceneConstName.{e.EnumName}Name }},");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        private static readonly Dictionary<string, SceneType> _fromName = new Dictionary<string, SceneType>();");
            sb.AppendLine();
            sb.AppendLine("        static SceneTypeMapping()");
            sb.AppendLine("        {");
            foreach (SceneEnumConfig.SceneEntry e in entries)
            {
                string address = GetSceneAddress(e);
                sb.AppendLine($"            _fromName[SceneConstName.{e.EnumName}Name] = SceneType.{e.EnumName};");
                // 规则2：资源地址与枚举名相同时跳过枚举名反向条目，避免重复 key（nameof(SceneType.Xxx) == 枚举名 == 资源地址）
                if (address != e.EnumName)
                {
                    sb.AppendLine($"            _fromName[nameof(SceneType.{e.EnumName})] = SceneType.{e.EnumName};");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>枚举 -> 资源地址；未匹配返回空串。</summary>");
            sb.AppendLine("        public static string GetSceneName(SceneType type)");
            sb.AppendLine("            => _toName.TryGetValue(type, out var name) ? name : string.Empty;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>资源地址或枚举名 -> 枚举；未匹配返回 null。</summary>");
            sb.AppendLine("        public static SceneType? GetSceneTypeFromName(string name)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (string.IsNullOrEmpty(name)) return null;");
            sb.AppendLine("            return _fromName.TryGetValue(name, out var type) ? type : (SceneType?)null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GetSceneAddress(SceneEnumConfig.SceneEntry entry)
        {
            if (entry.SceneAsset == null)
            {
                return entry.EnumName;
            }
            string path = AssetDatabase.GetAssetPath(entry.SceneAsset);
            return Path.GetFileNameWithoutExtension(path);
        }

        private static bool IsValidEnumName(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return false;
            }
            if (!char.IsLetter(name[0]) && name[0] != '_')
            {
                return false;
            }
            for (int i = 1; i < name.Length; i++)
            {
                if (!char.IsLetterOrDigit(name[i]) && name[i] != '_')
                {
                    return false;
                }
            }
            return true;
        }

        private static string EscapeXml(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }
            return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }

        private static void WriteFile(string path, string content)
        {
            File.WriteAllText(path, content);
        }
    }
}
