/// This file is auto-generated by Obfuz. Do not modify it.
///
/// Version: 0
/// SecretKey: Obfuz
/// OpCodeCount: 128

namespace Obfuz.EncryptionVM
{
    public class GeneratedEncryptionVirtualMachine : Obfuz.EncryptorBase
    {

        private const int kOpCodeBits = 7;

        private const int kOpCodeCount = 128;

        private const int kOpCodeMask = 127;



        private readonly int[] _secretKey;

        public GeneratedEncryptionVirtualMachine(byte[] secretKey)
        {
            this._secretKey = ConvertToIntKey(secretKey);
        }

        public override int OpCodeCount => kOpCodeCount;

        public override int Encrypt(int value, int opts, int salt)
        {
            uint uopts = (uint)opts;
            uint revertOps = 0;
            while (uopts != 0)
            {
                uint opCode = uopts & kOpCodeMask;
                revertOps <<= kOpCodeBits;
                revertOps |= opCode;
                uopts >>= kOpCodeBits;
            }

            while (revertOps != 0)
            {
                uint opCode = revertOps & kOpCodeMask;
                value = ExecuteEncrypt(value, (int)opCode, salt);
                revertOps >>= kOpCodeBits;
            }
            return value;
        }

        public override int Decrypt(int value, int opts, int salt)
        {
            uint uopts = (uint)opts;
            while (uopts != 0)
            {
                uint opCode = uopts & kOpCodeMask;
                value = ExecuteDecrypt(value, (int)opCode, salt);
                uopts >>= kOpCodeBits;
            }
            return value;
        }


        private int ExecuteEncrypt(int value, int opCode, int salt)
        {
            switch (opCode)
            {
                case 0:
                {
                    // MultipleInstruction
                    value = value * 598188269 + _secretKey[84] + salt;
                    return value;
                }
                case 1:
                {
                    // MultipleRotateXorInstruction
                    value = value * 1350058129 + _secretKey[136];
                    uint part1 = (uint)value << 4;
                    uint part2 = (uint)value >> (32 - 4);
                    value = (int)(part1 | part2);
                    value ^= 1817406469 ^ salt;
                    return value;
                }
                case 2:
                {
                    // MultipleXorRotateInstruction
                    value = value * -1144218503 + _secretKey[246];
                    value ^= -1498541961 ^ salt;
                    uint part1 = (uint)value << 5;
                    uint part2 = (uint)value >> (32 - 5);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 3:
                {
                    // AddRotateXorInstruction
                    value += -1207833585 + _secretKey[26];
                    uint part1 = (uint)value << 0;
                    uint part2 = (uint)value >> (32 - 0);
                    value = (int)(part1 | part2);
                    value ^= 29411710 ^ salt;
                    return value;
                }
                case 4:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 18;
                    uint part2 = (uint)value >> (32 - 18);
                    value = ((int)(part1 | part2) ^ _secretKey[85]) + salt;
                    return value;
                }
                case 5:
                {
                    // MultipleXorRotateInstruction
                    value = value * -1447238259 + _secretKey[165];
                    value ^= 86149918 ^ salt;
                    uint part1 = (uint)value << 0;
                    uint part2 = (uint)value >> (32 - 0);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 6:
                {
                    // AddRotateXorInstruction
                    value += -1856354856 + _secretKey[178];
                    uint part1 = (uint)value << 29;
                    uint part2 = (uint)value >> (32 - 29);
                    value = (int)(part1 | part2);
                    value ^= -1262500500 ^ salt;
                    return value;
                }
                case 7:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[53]) + salt) ^ 665464645;
                    return value;
                }
                case 8:
                {
                    // XorMultipleRotateInstruction
                    value ^= -1044567439 ^ salt;
                    value = value * -1860181607 + _secretKey[206];
                    uint part1 = (uint)value << 16;
                    uint part2 = (uint)value >> (32 - 16);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 9:
                {
                    // MultipleInstruction
                    value = value * 522878123 + _secretKey[196] + salt;
                    return value;
                }
                case 10:
                {
                    // XorAddRotateInstruction
                    value ^= -755609206 ^ salt;
                    value += -1035239660 + _secretKey[199];
                    uint part1 = (uint)value << 10;
                    uint part2 = (uint)value >> (32 - 10);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 11:
                {
                    // AddInstruction
                    value = ((value + _secretKey[89]) ^ salt) + -1177184477;
                    return value;
                }
                case 12:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 29;
                    uint part2 = (uint)value >> (32 - 29);
                    value = ((int)(part1 | part2) ^ _secretKey[23]) + salt;
                    return value;
                }
                case 13:
                {
                    // XorMultipleRotateInstruction
                    value ^= -1510419150 ^ salt;
                    value = value * -93709937 + _secretKey[68];
                    uint part1 = (uint)value << 19;
                    uint part2 = (uint)value >> (32 - 19);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 14:
                {
                    // MultipleRotateXorInstruction
                    value = value * 2015893433 + _secretKey[156];
                    uint part1 = (uint)value << 6;
                    uint part2 = (uint)value >> (32 - 6);
                    value = (int)(part1 | part2);
                    value ^= -1134639492 ^ salt;
                    return value;
                }
                case 15:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 7;
                    uint part2 = (uint)value >> (32 - 7);
                    value = ((int)(part1 | part2) ^ _secretKey[95]) + salt;
                    return value;
                }
                case 16:
                {
                    // XorMultipleRotateInstruction
                    value ^= -759315565 ^ salt;
                    value = value * -436699251 + _secretKey[79];
                    uint part1 = (uint)value << 6;
                    uint part2 = (uint)value >> (32 - 6);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 17:
                {
                    // MultipleRotateXorInstruction
                    value = value * 1266530571 + _secretKey[75];
                    uint part1 = (uint)value << 2;
                    uint part2 = (uint)value >> (32 - 2);
                    value = (int)(part1 | part2);
                    value ^= -3885258 ^ salt;
                    return value;
                }
                case 18:
                {
                    // MultipleXorRotateInstruction
                    value = value * -259404705 + _secretKey[153];
                    value ^= 1207613963 ^ salt;
                    uint part1 = (uint)value << 9;
                    uint part2 = (uint)value >> (32 - 9);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 19:
                {
                    // MultipleRotateXorInstruction
                    value = value * 1042624059 + _secretKey[86];
                    uint part1 = (uint)value << 11;
                    uint part2 = (uint)value >> (32 - 11);
                    value = (int)(part1 | part2);
                    value ^= 792769043 ^ salt;
                    return value;
                }
                case 20:
                {
                    // AddInstruction
                    value = ((value + _secretKey[194]) ^ salt) + -512520382;
                    return value;
                }
                case 21:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[195]) + salt) ^ -1864951858;
                    return value;
                }
                case 22:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 15;
                    uint part2 = (uint)value >> (32 - 15);
                    value = ((int)(part1 | part2) ^ _secretKey[2]) + salt;
                    return value;
                }
                case 23:
                {
                    // MultipleInstruction
                    value = value * -463118297 + _secretKey[203] + salt;
                    return value;
                }
                case 24:
                {
                    // AddInstruction
                    value = ((value + _secretKey[110]) ^ salt) + 2026667919;
                    return value;
                }
                case 25:
                {
                    // AddXorRotateInstruction
                    value += 848657810 + _secretKey[133];
                    value ^= 392708821 ^ salt;
                    uint part1 = (uint)value << 15;
                    uint part2 = (uint)value >> (32 - 15);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 26:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 5;
                    uint part2 = (uint)value >> (32 - 5);
                    value = ((int)(part1 | part2) ^ _secretKey[93]) + salt;
                    return value;
                }
                case 27:
                {
                    // XorAddRotateInstruction
                    value ^= 1294662302 ^ salt;
                    value += 1284012732 + _secretKey[58];
                    uint part1 = (uint)value << 30;
                    uint part2 = (uint)value >> (32 - 30);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 28:
                {
                    // XorMultipleRotateInstruction
                    value ^= -1438081752 ^ salt;
                    value = value * -1171400509 + _secretKey[138];
                    uint part1 = (uint)value << 29;
                    uint part2 = (uint)value >> (32 - 29);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 29:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 6;
                    uint part2 = (uint)value >> (32 - 6);
                    value = ((int)(part1 | part2) ^ _secretKey[240]) + salt;
                    return value;
                }
                case 30:
                {
                    // MultipleRotateXorInstruction
                    value = value * 1892661727 + _secretKey[215];
                    uint part1 = (uint)value << 24;
                    uint part2 = (uint)value >> (32 - 24);
                    value = (int)(part1 | part2);
                    value ^= 1594594445 ^ salt;
                    return value;
                }
                case 31:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 19;
                    uint part2 = (uint)value >> (32 - 19);
                    value = ((int)(part1 | part2) ^ _secretKey[49]) + salt;
                    return value;
                }
                case 32:
                {
                    // XorAddRotateInstruction
                    value ^= 226193183 ^ salt;
                    value += -1038657413 + _secretKey[247];
                    uint part1 = (uint)value << 17;
                    uint part2 = (uint)value >> (32 - 17);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 33:
                {
                    // XorAddRotateInstruction
                    value ^= -484591087 ^ salt;
                    value += 459902223 + _secretKey[252];
                    uint part1 = (uint)value << 23;
                    uint part2 = (uint)value >> (32 - 23);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 34:
                {
                    // MultipleXorRotateInstruction
                    value = value * -1382643267 + _secretKey[211];
                    value ^= 1186351980 ^ salt;
                    uint part1 = (uint)value << 14;
                    uint part2 = (uint)value >> (32 - 14);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 35:
                {
                    // XorAddRotateInstruction
                    value ^= 1658142493 ^ salt;
                    value += -283413931 + _secretKey[235];
                    uint part1 = (uint)value << 15;
                    uint part2 = (uint)value >> (32 - 15);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 36:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[90]) + salt) ^ -1892941953;
                    return value;
                }
                case 37:
                {
                    // XorMultipleRotateInstruction
                    value ^= -1297440001 ^ salt;
                    value = value * -1166749617 + _secretKey[111];
                    uint part1 = (uint)value << 31;
                    uint part2 = (uint)value >> (32 - 31);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 38:
                {
                    // MultipleRotateXorInstruction
                    value = value * -375439505 + _secretKey[213];
                    uint part1 = (uint)value << 31;
                    uint part2 = (uint)value >> (32 - 31);
                    value = (int)(part1 | part2);
                    value ^= 1353158598 ^ salt;
                    return value;
                }
                case 39:
                {
                    // XorAddRotateInstruction
                    value ^= -934836680 ^ salt;
                    value += 873171360 + _secretKey[72];
                    uint part1 = (uint)value << 20;
                    uint part2 = (uint)value >> (32 - 20);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 40:
                {
                    // MultipleXorRotateInstruction
                    value = value * 1427441479 + _secretKey[140];
                    value ^= -28088263 ^ salt;
                    uint part1 = (uint)value << 18;
                    uint part2 = (uint)value >> (32 - 18);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 41:
                {
                    // AddRotateXorInstruction
                    value += 969234286 + _secretKey[116];
                    uint part1 = (uint)value << 1;
                    uint part2 = (uint)value >> (32 - 1);
                    value = (int)(part1 | part2);
                    value ^= -312111197 ^ salt;
                    return value;
                }
                case 42:
                {
                    // MultipleInstruction
                    value = value * -1130955295 + _secretKey[29] + salt;
                    return value;
                }
                case 43:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 28;
                    uint part2 = (uint)value >> (32 - 28);
                    value = ((int)(part1 | part2) ^ _secretKey[1]) + salt;
                    return value;
                }
                case 44:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 4;
                    uint part2 = (uint)value >> (32 - 4);
                    value = ((int)(part1 | part2) ^ _secretKey[184]) + salt;
                    return value;
                }
                case 45:
                {
                    // MultipleXorRotateInstruction
                    value = value * -1782633617 + _secretKey[199];
                    value ^= 1068062556 ^ salt;
                    uint part1 = (uint)value << 18;
                    uint part2 = (uint)value >> (32 - 18);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 46:
                {
                    // XorMultipleRotateInstruction
                    value ^= 196245895 ^ salt;
                    value = value * -1852817781 + _secretKey[200];
                    uint part1 = (uint)value << 1;
                    uint part2 = (uint)value >> (32 - 1);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 47:
                {
                    // MultipleXorRotateInstruction
                    value = value * -50587953 + _secretKey[10];
                    value ^= -1964107221 ^ salt;
                    uint part1 = (uint)value << 7;
                    uint part2 = (uint)value >> (32 - 7);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 48:
                {
                    // MultipleXorRotateInstruction
                    value = value * 1216851115 + _secretKey[238];
                    value ^= -38668552 ^ salt;
                    uint part1 = (uint)value << 18;
                    uint part2 = (uint)value >> (32 - 18);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 49:
                {
                    // MultipleInstruction
                    value = value * -2133817615 + _secretKey[172] + salt;
                    return value;
                }
                case 50:
                {
                    // AddXorRotateInstruction
                    value += 1412414820 + _secretKey[219];
                    value ^= -2098495662 ^ salt;
                    uint part1 = (uint)value << 11;
                    uint part2 = (uint)value >> (32 - 11);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 51:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 10;
                    uint part2 = (uint)value >> (32 - 10);
                    value = ((int)(part1 | part2) ^ _secretKey[97]) + salt;
                    return value;
                }
                case 52:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1791837593 + _secretKey[63];
                    uint part1 = (uint)value << 24;
                    uint part2 = (uint)value >> (32 - 24);
                    value = (int)(part1 | part2);
                    value ^= -21948406 ^ salt;
                    return value;
                }
                case 53:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 7;
                    uint part2 = (uint)value >> (32 - 7);
                    value = ((int)(part1 | part2) ^ _secretKey[221]) + salt;
                    return value;
                }
                case 54:
                {
                    // MultipleInstruction
                    value = value * -1220403071 + _secretKey[96] + salt;
                    return value;
                }
                case 55:
                {
                    // MultipleRotateXorInstruction
                    value = value * -867896207 + _secretKey[29];
                    uint part1 = (uint)value << 29;
                    uint part2 = (uint)value >> (32 - 29);
                    value = (int)(part1 | part2);
                    value ^= -1022882984 ^ salt;
                    return value;
                }
                case 56:
                {
                    // XorMultipleRotateInstruction
                    value ^= 2122077674 ^ salt;
                    value = value * 957274637 + _secretKey[235];
                    uint part1 = (uint)value << 12;
                    uint part2 = (uint)value >> (32 - 12);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 57:
                {
                    // AddRotateXorInstruction
                    value += -503448718 + _secretKey[175];
                    uint part1 = (uint)value << 21;
                    uint part2 = (uint)value >> (32 - 21);
                    value = (int)(part1 | part2);
                    value ^= -720824840 ^ salt;
                    return value;
                }
                case 58:
                {
                    // MultipleInstruction
                    value = value * -280528271 + _secretKey[231] + salt;
                    return value;
                }
                case 59:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 19;
                    uint part2 = (uint)value >> (32 - 19);
                    value = ((int)(part1 | part2) ^ _secretKey[75]) + salt;
                    return value;
                }
                case 60:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1403438719 + _secretKey[171];
                    uint part1 = (uint)value << 27;
                    uint part2 = (uint)value >> (32 - 27);
                    value = (int)(part1 | part2);
                    value ^= 1420744071 ^ salt;
                    return value;
                }
                case 61:
                {
                    // XorMultipleRotateInstruction
                    value ^= 1366253139 ^ salt;
                    value = value * -1583570963 + _secretKey[84];
                    uint part1 = (uint)value << 15;
                    uint part2 = (uint)value >> (32 - 15);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 62:
                {
                    // MultipleXorRotateInstruction
                    value = value * 24444809 + _secretKey[132];
                    value ^= -1974823163 ^ salt;
                    uint part1 = (uint)value << 6;
                    uint part2 = (uint)value >> (32 - 6);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 63:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 22;
                    uint part2 = (uint)value >> (32 - 22);
                    value = ((int)(part1 | part2) ^ _secretKey[119]) + salt;
                    return value;
                }
                case 64:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[15]) + salt) ^ 1262347216;
                    return value;
                }
                case 65:
                {
                    // AddInstruction
                    value = ((value + _secretKey[126]) ^ salt) + 1780280992;
                    return value;
                }
                case 66:
                {
                    // MultipleXorRotateInstruction
                    value = value * -1871888237 + _secretKey[85];
                    value ^= -1198162446 ^ salt;
                    uint part1 = (uint)value << 13;
                    uint part2 = (uint)value >> (32 - 13);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 67:
                {
                    // MultipleInstruction
                    value = value * 931252767 + _secretKey[128] + salt;
                    return value;
                }
                case 68:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 24;
                    uint part2 = (uint)value >> (32 - 24);
                    value = ((int)(part1 | part2) ^ _secretKey[178]) + salt;
                    return value;
                }
                case 69:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[61]) + salt) ^ 1649427052;
                    return value;
                }
                case 70:
                {
                    // MultipleRotateXorInstruction
                    value = value * -100486091 + _secretKey[83];
                    uint part1 = (uint)value << 17;
                    uint part2 = (uint)value >> (32 - 17);
                    value = (int)(part1 | part2);
                    value ^= 849172121 ^ salt;
                    return value;
                }
                case 71:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 16;
                    uint part2 = (uint)value >> (32 - 16);
                    value = ((int)(part1 | part2) ^ _secretKey[169]) + salt;
                    return value;
                }
                case 72:
                {
                    // XorAddRotateInstruction
                    value ^= 1068287172 ^ salt;
                    value += -2092062916 + _secretKey[138];
                    uint part1 = (uint)value << 20;
                    uint part2 = (uint)value >> (32 - 20);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 73:
                {
                    // MultipleInstruction
                    value = value * -729679733 + _secretKey[34] + salt;
                    return value;
                }
                case 74:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1624925351 + _secretKey[30];
                    uint part1 = (uint)value << 29;
                    uint part2 = (uint)value >> (32 - 29);
                    value = (int)(part1 | part2);
                    value ^= -145743337 ^ salt;
                    return value;
                }
                case 75:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1768166349 + _secretKey[142];
                    uint part1 = (uint)value << 4;
                    uint part2 = (uint)value >> (32 - 4);
                    value = (int)(part1 | part2);
                    value ^= 280941267 ^ salt;
                    return value;
                }
                case 76:
                {
                    // MultipleInstruction
                    value = value * -1708700487 + _secretKey[156] + salt;
                    return value;
                }
                case 77:
                {
                    // AddRotateXorInstruction
                    value += 314625916 + _secretKey[192];
                    uint part1 = (uint)value << 7;
                    uint part2 = (uint)value >> (32 - 7);
                    value = (int)(part1 | part2);
                    value ^= 827331935 ^ salt;
                    return value;
                }
                case 78:
                {
                    // MultipleInstruction
                    value = value * 875189907 + _secretKey[141] + salt;
                    return value;
                }
                case 79:
                {
                    // AddXorRotateInstruction
                    value += 1607953190 + _secretKey[133];
                    value ^= -11549173 ^ salt;
                    uint part1 = (uint)value << 11;
                    uint part2 = (uint)value >> (32 - 11);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 80:
                {
                    // XorAddRotateInstruction
                    value ^= -1454482890 ^ salt;
                    value += 687186546 + _secretKey[95];
                    uint part1 = (uint)value << 25;
                    uint part2 = (uint)value >> (32 - 25);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 81:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[195]) + salt) ^ 814860713;
                    return value;
                }
                case 82:
                {
                    // AddRotateXorInstruction
                    value += 1998643542 + _secretKey[171];
                    uint part1 = (uint)value << 19;
                    uint part2 = (uint)value >> (32 - 19);
                    value = (int)(part1 | part2);
                    value ^= 213310246 ^ salt;
                    return value;
                }
                case 83:
                {
                    // AddRotateXorInstruction
                    value += 542686146 + _secretKey[249];
                    uint part1 = (uint)value << 14;
                    uint part2 = (uint)value >> (32 - 14);
                    value = (int)(part1 | part2);
                    value ^= -696314173 ^ salt;
                    return value;
                }
                case 84:
                {
                    // AddRotateXorInstruction
                    value += 1734820207 + _secretKey[2];
                    uint part1 = (uint)value << 9;
                    uint part2 = (uint)value >> (32 - 9);
                    value = (int)(part1 | part2);
                    value ^= 118718247 ^ salt;
                    return value;
                }
                case 85:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[143]) + salt) ^ 1553710234;
                    return value;
                }
                case 86:
                {
                    // AddRotateXorInstruction
                    value += -217984331 + _secretKey[146];
                    uint part1 = (uint)value << 5;
                    uint part2 = (uint)value >> (32 - 5);
                    value = (int)(part1 | part2);
                    value ^= -1402843691 ^ salt;
                    return value;
                }
                case 87:
                {
                    // MultipleInstruction
                    value = value * 1078374119 + _secretKey[5] + salt;
                    return value;
                }
                case 88:
                {
                    // MultipleRotateXorInstruction
                    value = value * -975647447 + _secretKey[158];
                    uint part1 = (uint)value << 28;
                    uint part2 = (uint)value >> (32 - 28);
                    value = (int)(part1 | part2);
                    value ^= -2044505542 ^ salt;
                    return value;
                }
                case 89:
                {
                    // AddInstruction
                    value = ((value + _secretKey[40]) ^ salt) + -1213654475;
                    return value;
                }
                case 90:
                {
                    // XorMultipleRotateInstruction
                    value ^= -1886972278 ^ salt;
                    value = value * 275510141 + _secretKey[206];
                    uint part1 = (uint)value << 6;
                    uint part2 = (uint)value >> (32 - 6);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 91:
                {
                    // AddRotateXorInstruction
                    value += -1724625239 + _secretKey[223];
                    uint part1 = (uint)value << 23;
                    uint part2 = (uint)value >> (32 - 23);
                    value = (int)(part1 | part2);
                    value ^= -979249928 ^ salt;
                    return value;
                }
                case 92:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[83]) + salt) ^ -1104541704;
                    return value;
                }
                case 93:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[31]) + salt) ^ 311150152;
                    return value;
                }
                case 94:
                {
                    // XorMultipleRotateInstruction
                    value ^= 116496631 ^ salt;
                    value = value * 13120561 + _secretKey[176];
                    uint part1 = (uint)value << 17;
                    uint part2 = (uint)value >> (32 - 17);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 95:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1932552195 + _secretKey[87];
                    uint part1 = (uint)value << 2;
                    uint part2 = (uint)value >> (32 - 2);
                    value = (int)(part1 | part2);
                    value ^= 2133438141 ^ salt;
                    return value;
                }
                case 96:
                {
                    // MultipleRotateXorInstruction
                    value = value * 126641773 + _secretKey[174];
                    uint part1 = (uint)value << 16;
                    uint part2 = (uint)value >> (32 - 16);
                    value = (int)(part1 | part2);
                    value ^= 225535005 ^ salt;
                    return value;
                }
                case 97:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1013570837 + _secretKey[175];
                    uint part1 = (uint)value << 1;
                    uint part2 = (uint)value >> (32 - 1);
                    value = (int)(part1 | part2);
                    value ^= -1703839105 ^ salt;
                    return value;
                }
                case 98:
                {
                    // XorAddRotateInstruction
                    value ^= -447564571 ^ salt;
                    value += -1783079937 + _secretKey[78];
                    uint part1 = (uint)value << 15;
                    uint part2 = (uint)value >> (32 - 15);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 99:
                {
                    // XorInstruction
                    value = ((value ^ _secretKey[111]) + salt) ^ -316631669;
                    return value;
                }
                case 100:
                {
                    // XorMultipleRotateInstruction
                    value ^= -405694625 ^ salt;
                    value = value * 1711408839 + _secretKey[252];
                    uint part1 = (uint)value << 24;
                    uint part2 = (uint)value >> (32 - 24);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 101:
                {
                    // MultipleXorRotateInstruction
                    value = value * -910384311 + _secretKey[212];
                    value ^= -1551058348 ^ salt;
                    uint part1 = (uint)value << 6;
                    uint part2 = (uint)value >> (32 - 6);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 102:
                {
                    // AddInstruction
                    value = ((value + _secretKey[18]) ^ salt) + -853736135;
                    return value;
                }
                case 103:
                {
                    // AddInstruction
                    value = ((value + _secretKey[116]) ^ salt) + 1321376878;
                    return value;
                }
                case 104:
                {
                    // MultipleRotateXorInstruction
                    value = value * 1039555235 + _secretKey[7];
                    uint part1 = (uint)value << 0;
                    uint part2 = (uint)value >> (32 - 0);
                    value = (int)(part1 | part2);
                    value ^= 541697309 ^ salt;
                    return value;
                }
                case 105:
                {
                    // AddRotateXorInstruction
                    value += -822594180 + _secretKey[1];
                    uint part1 = (uint)value << 4;
                    uint part2 = (uint)value >> (32 - 4);
                    value = (int)(part1 | part2);
                    value ^= 1176608900 ^ salt;
                    return value;
                }
                case 106:
                {
                    // AddInstruction
                    value = ((value + _secretKey[110]) ^ salt) + -882893600;
                    return value;
                }
                case 107:
                {
                    // MultipleRotateXorInstruction
                    value = value * -346726819 + _secretKey[114];
                    uint part1 = (uint)value << 23;
                    uint part2 = (uint)value >> (32 - 23);
                    value = (int)(part1 | part2);
                    value ^= -1566546809 ^ salt;
                    return value;
                }
                case 108:
                {
                    // MultipleInstruction
                    value = value * -981516343 + _secretKey[97] + salt;
                    return value;
                }
                case 109:
                {
                    // XorAddRotateInstruction
                    value ^= -72794161 ^ salt;
                    value += 1161425930 + _secretKey[43];
                    uint part1 = (uint)value << 7;
                    uint part2 = (uint)value >> (32 - 7);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 110:
                {
                    // AddInstruction
                    value = ((value + _secretKey[238]) ^ salt) + -1619543125;
                    return value;
                }
                case 111:
                {
                    // XorAddRotateInstruction
                    value ^= 1170459122 ^ salt;
                    value += -1766468683 + _secretKey[241];
                    uint part1 = (uint)value << 12;
                    uint part2 = (uint)value >> (32 - 12);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 112:
                {
                    // AddXorRotateInstruction
                    value += 251687012 + _secretKey[219];
                    value ^= 323019346 ^ salt;
                    uint part1 = (uint)value << 11;
                    uint part2 = (uint)value >> (32 - 11);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 113:
                {
                    // AddInstruction
                    value = ((value + _secretKey[97]) ^ salt) + -1049972438;
                    return value;
                }
                case 114:
                {
                    // XorMultipleRotateInstruction
                    value ^= -492239002 ^ salt;
                    value = value * -1496840897 + _secretKey[216];
                    uint part1 = (uint)value << 10;
                    uint part2 = (uint)value >> (32 - 10);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 115:
                {
                    // AddInstruction
                    value = ((value + _secretKey[221]) ^ salt) + -748126329;
                    return value;
                }
                case 116:
                {
                    // AddXorRotateInstruction
                    value += -441051263 + _secretKey[96];
                    value ^= -5933889 ^ salt;
                    uint part1 = (uint)value << 17;
                    uint part2 = (uint)value >> (32 - 17);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 117:
                {
                    // MultipleRotateXorInstruction
                    value = value * -1850062787 + _secretKey[88];
                    uint part1 = (uint)value << 11;
                    uint part2 = (uint)value >> (32 - 11);
                    value = (int)(part1 | part2);
                    value ^= 543895274 ^ salt;
                    return value;
                }
                case 118:
                {
                    // MultipleInstruction
                    value = value * -747527445 + _secretKey[140] + salt;
                    return value;
                }
                case 119:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 18;
                    uint part2 = (uint)value >> (32 - 18);
                    value = ((int)(part1 | part2) ^ _secretKey[175]) + salt;
                    return value;
                }
                case 120:
                {
                    // MultipleRotateXorInstruction
                    value = value * 345252089 + _secretKey[57];
                    uint part1 = (uint)value << 16;
                    uint part2 = (uint)value >> (32 - 16);
                    value = (int)(part1 | part2);
                    value ^= 1300544743 ^ salt;
                    return value;
                }
                case 121:
                {
                    // XorAddRotateInstruction
                    value ^= -547380749 ^ salt;
                    value += 678597707 + _secretKey[119];
                    uint part1 = (uint)value << 1;
                    uint part2 = (uint)value >> (32 - 1);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 122:
                {
                    // XorMultipleRotateInstruction
                    value ^= 683601851 ^ salt;
                    value = value * -145367929 + _secretKey[191];
                    uint part1 = (uint)value << 19;
                    uint part2 = (uint)value >> (32 - 19);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 123:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 20;
                    uint part2 = (uint)value >> (32 - 20);
                    value = ((int)(part1 | part2) ^ _secretKey[15]) + salt;
                    return value;
                }
                case 124:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 8;
                    uint part2 = (uint)value >> (32 - 8);
                    value = ((int)(part1 | part2) ^ _secretKey[132]) + salt;
                    return value;
                }
                case 125:
                {
                    // MultipleInstruction
                    value = value * 1436085223 + _secretKey[120] + salt;
                    return value;
                }
                case 126:
                {
                    // AddInstruction
                    value = ((value + _secretKey[197]) ^ salt) + -1374139785;
                    return value;
                }
                case 127:
                {
                    // BitRotateInstruction
                    uint part1 = (uint)value << 15;
                    uint part2 = (uint)value >> (32 - 15);
                    value = ((int)(part1 | part2) ^ _secretKey[26]) + salt;
                    return value;
                }

                default: throw new System.Exception($"Invalid opCode:{opCode}");
            }
        }

        private int ExecuteDecrypt(int value, int opCode, int salt)
        {
            switch (opCode)
            {
                case 0:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[84] - salt) * -1954824987;
                    return value;
                }
                case 1:
                {
                    // MultipleRotateXorInstruction
                    value ^= 1817406469 ^ salt;
                    uint value2 = (uint)value >> 4;
                    uint part1 = (uint)value << (32 - 4);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[136]) * -2114748303;
                    return value;
                }
                case 2:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 5;
                    uint part1 = (uint)value << (32 - 5);
                    value = (int)(value2 | part1);
                    value ^= -1498541961 ^ salt;
                    value = (value - _secretKey[246]) * -203485751;
                    return value;
                }
                case 3:
                {
                    // AddRotateXorInstruction
                    value ^= 29411710 ^ salt;
                    uint value2 = (uint)value >> 0;
                    uint part1 = (uint)value << (32 - 0);
                    value = (int)(value2 | part1);
                    value -= -1207833585 + _secretKey[26];
                    return value;
                }
                case 4:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[85]);
                    uint part1 = value2 >> 18;
                    uint part2 = value2 << (32 - 18);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 5:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 0;
                    uint part1 = (uint)value << (32 - 0);
                    value = (int)(value2 | part1);
                    value ^= 86149918 ^ salt;
                    value = (value - _secretKey[165]) * -327424699;
                    return value;
                }
                case 6:
                {
                    // AddRotateXorInstruction
                    value ^= -1262500500 ^ salt;
                    uint value2 = (uint)value >> 29;
                    uint part1 = (uint)value << (32 - 29);
                    value = (int)(value2 | part1);
                    value -= -1856354856 + _secretKey[178];
                    return value;
                }
                case 7:
                {
                    // XorInstruction
                    value = ((value ^ 665464645) - salt) ^ _secretKey[53];
                    return value;
                }
                case 8:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 16;
                    uint part1 = (uint)value << (32 - 16);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[206]) * -1476140375;
                    value ^= -1044567439 ^ salt;
                    return value;
                }
                case 9:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[196] - salt) * 2125307395;
                    return value;
                }
                case 10:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 10;
                    uint part1 = (uint)value << (32 - 10);
                    value = (int)(value2 | part1);
                    value -= -1035239660 + _secretKey[199];
                    value ^= -755609206 ^ salt;
                    return value;
                }
                case 11:
                {
                    // AddInstruction
                    value = ((value - -1177184477) ^ salt) - _secretKey[89];
                    return value;
                }
                case 12:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[23]);
                    uint part1 = value2 >> 29;
                    uint part2 = value2 << (32 - 29);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 13:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 19;
                    uint part1 = (uint)value << (32 - 19);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[68]) * 1170138479;
                    value ^= -1510419150 ^ salt;
                    return value;
                }
                case 14:
                {
                    // MultipleRotateXorInstruction
                    value ^= -1134639492 ^ salt;
                    uint value2 = (uint)value >> 6;
                    uint part1 = (uint)value << (32 - 6);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[156]) * 275824265;
                    return value;
                }
                case 15:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[95]);
                    uint part1 = value2 >> 7;
                    uint part2 = value2 << (32 - 7);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 16:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 6;
                    uint part1 = (uint)value << (32 - 6);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[79]) * 1552472901;
                    value ^= -759315565 ^ salt;
                    return value;
                }
                case 17:
                {
                    // MultipleRotateXorInstruction
                    value ^= -3885258 ^ salt;
                    uint value2 = (uint)value >> 2;
                    uint part1 = (uint)value << (32 - 2);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[75]) * -1943909725;
                    return value;
                }
                case 18:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 9;
                    uint part1 = (uint)value << (32 - 9);
                    value = (int)(value2 | part1);
                    value ^= 1207613963 ^ salt;
                    value = (value - _secretKey[153]) * 1985974175;
                    return value;
                }
                case 19:
                {
                    // MultipleRotateXorInstruction
                    value ^= 792769043 ^ salt;
                    uint value2 = (uint)value >> 11;
                    uint part1 = (uint)value << (32 - 11);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[86]) * 1412922099;
                    return value;
                }
                case 20:
                {
                    // AddInstruction
                    value = ((value - -512520382) ^ salt) - _secretKey[194];
                    return value;
                }
                case 21:
                {
                    // XorInstruction
                    value = ((value ^ -1864951858) - salt) ^ _secretKey[195];
                    return value;
                }
                case 22:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[2]);
                    uint part1 = value2 >> 15;
                    uint part2 = value2 << (32 - 15);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 23:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[203] - salt) * 891162519;
                    return value;
                }
                case 24:
                {
                    // AddInstruction
                    value = ((value - 2026667919) ^ salt) - _secretKey[110];
                    return value;
                }
                case 25:
                {
                    // AddXorRotateInstruction
                    uint part1 = (uint)value >> 15;
                    uint part2 = (uint)value << (32 - 15);
                    value = (int)(part1 | part2);
                    value ^= 392708821 ^ salt;
                    value -= 848657810 + _secretKey[133];
                    return value;
                }
                case 26:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[93]);
                    uint part1 = value2 >> 5;
                    uint part2 = value2 << (32 - 5);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 27:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 30;
                    uint part1 = (uint)value << (32 - 30);
                    value = (int)(value2 | part1);
                    value -= 1284012732 + _secretKey[58];
                    value ^= 1294662302 ^ salt;
                    return value;
                }
                case 28:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 29;
                    uint part1 = (uint)value << (32 - 29);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[138]) * -708470805;
                    value ^= -1438081752 ^ salt;
                    return value;
                }
                case 29:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[240]);
                    uint part1 = value2 >> 6;
                    uint part2 = value2 << (32 - 6);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 30:
                {
                    // MultipleRotateXorInstruction
                    value ^= 1594594445 ^ salt;
                    uint value2 = (uint)value >> 24;
                    uint part1 = (uint)value << (32 - 24);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[215]) * 1857241631;
                    return value;
                }
                case 31:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[49]);
                    uint part1 = value2 >> 19;
                    uint part2 = value2 << (32 - 19);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 32:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 17;
                    uint part1 = (uint)value << (32 - 17);
                    value = (int)(value2 | part1);
                    value -= -1038657413 + _secretKey[247];
                    value ^= 226193183 ^ salt;
                    return value;
                }
                case 33:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 23;
                    uint part1 = (uint)value << (32 - 23);
                    value = (int)(value2 | part1);
                    value -= 459902223 + _secretKey[252];
                    value ^= -484591087 ^ salt;
                    return value;
                }
                case 34:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 14;
                    uint part1 = (uint)value << (32 - 14);
                    value = (int)(value2 | part1);
                    value ^= 1186351980 ^ salt;
                    value = (value - _secretKey[211]) * 1159592341;
                    return value;
                }
                case 35:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 15;
                    uint part1 = (uint)value << (32 - 15);
                    value = (int)(value2 | part1);
                    value -= -283413931 + _secretKey[235];
                    value ^= 1658142493 ^ salt;
                    return value;
                }
                case 36:
                {
                    // XorInstruction
                    value = ((value ^ -1892941953) - salt) ^ _secretKey[90];
                    return value;
                }
                case 37:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 31;
                    uint part1 = (uint)value << (32 - 31);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[111]) * -674216273;
                    value ^= -1297440001 ^ salt;
                    return value;
                }
                case 38:
                {
                    // MultipleRotateXorInstruction
                    value ^= 1353158598 ^ salt;
                    uint value2 = (uint)value >> 31;
                    uint part1 = (uint)value << (32 - 31);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[213]) * 803536783;
                    return value;
                }
                case 39:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 20;
                    uint part1 = (uint)value << (32 - 20);
                    value = (int)(value2 | part1);
                    value -= 873171360 + _secretKey[72];
                    value ^= -934836680 ^ salt;
                    return value;
                }
                case 40:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 18;
                    uint part1 = (uint)value << (32 - 18);
                    value = (int)(value2 | part1);
                    value ^= -28088263 ^ salt;
                    value = (value - _secretKey[140]) * 1881436791;
                    return value;
                }
                case 41:
                {
                    // AddRotateXorInstruction
                    value ^= -312111197 ^ salt;
                    uint value2 = (uint)value >> 1;
                    uint part1 = (uint)value << (32 - 1);
                    value = (int)(value2 | part1);
                    value -= 969234286 + _secretKey[116];
                    return value;
                }
                case 42:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[29] - salt) * 2102789665;
                    return value;
                }
                case 43:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[1]);
                    uint part1 = value2 >> 28;
                    uint part2 = value2 << (32 - 28);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 44:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[184]);
                    uint part1 = value2 >> 4;
                    uint part2 = value2 << (32 - 4);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 45:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 18;
                    uint part1 = (uint)value << (32 - 18);
                    value = (int)(value2 | part1);
                    value ^= 1068062556 ^ salt;
                    value = (value - _secretKey[199]) * 85627791;
                    return value;
                }
                case 46:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 1;
                    uint part1 = (uint)value << (32 - 1);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[200]) * 1138735395;
                    value ^= 196245895 ^ salt;
                    return value;
                }
                case 47:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 7;
                    uint part1 = (uint)value << (32 - 7);
                    value = (int)(value2 | part1);
                    value ^= -1964107221 ^ salt;
                    value = (value - _secretKey[10]) * -1413533649;
                    return value;
                }
                case 48:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 18;
                    uint part1 = (uint)value << (32 - 18);
                    value = (int)(value2 | part1);
                    value ^= -38668552 ^ salt;
                    value = (value - _secretKey[238]) * 665251331;
                    return value;
                }
                case 49:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[172] - salt) * -818173423;
                    return value;
                }
                case 50:
                {
                    // AddXorRotateInstruction
                    uint part1 = (uint)value >> 11;
                    uint part2 = (uint)value << (32 - 11);
                    value = (int)(part1 | part2);
                    value ^= -2098495662 ^ salt;
                    value -= 1412414820 + _secretKey[219];
                    return value;
                }
                case 51:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[97]);
                    uint part1 = value2 >> 10;
                    uint part2 = value2 << (32 - 10);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 52:
                {
                    // MultipleRotateXorInstruction
                    value ^= -21948406 ^ salt;
                    uint value2 = (uint)value >> 24;
                    uint part1 = (uint)value << (32 - 24);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[63]) * -99761833;
                    return value;
                }
                case 53:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[221]);
                    uint part1 = value2 >> 7;
                    uint part2 = value2 << (32 - 7);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 54:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[96] - salt) * -2034360447;
                    return value;
                }
                case 55:
                {
                    // MultipleRotateXorInstruction
                    value ^= -1022882984 ^ salt;
                    uint value2 = (uint)value >> 29;
                    uint part1 = (uint)value << (32 - 29);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[29]) * -899658607;
                    return value;
                }
                case 56:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 12;
                    uint part1 = (uint)value << (32 - 12);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[235]) * 340919493;
                    value ^= 2122077674 ^ salt;
                    return value;
                }
                case 57:
                {
                    // AddRotateXorInstruction
                    value ^= -720824840 ^ salt;
                    uint value2 = (uint)value >> 21;
                    uint part1 = (uint)value << (32 - 21);
                    value = (int)(value2 | part1);
                    value -= -503448718 + _secretKey[175];
                    return value;
                }
                case 58:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[231] - salt) * 913639057;
                    return value;
                }
                case 59:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[75]);
                    uint part1 = value2 >> 19;
                    uint part2 = value2 << (32 - 19);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 60:
                {
                    // MultipleRotateXorInstruction
                    value ^= 1420744071 ^ salt;
                    uint value2 = (uint)value >> 27;
                    uint part1 = (uint)value << (32 - 27);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[171]) * 238093953;
                    return value;
                }
                case 61:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 15;
                    uint part1 = (uint)value << (32 - 15);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[84]) * -2096065051;
                    value ^= 1366253139 ^ salt;
                    return value;
                }
                case 62:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 6;
                    uint part1 = (uint)value << (32 - 6);
                    value = (int)(value2 | part1);
                    value ^= -1974823163 ^ salt;
                    value = (value - _secretKey[132]) * 303900345;
                    return value;
                }
                case 63:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[119]);
                    uint part1 = value2 >> 22;
                    uint part2 = value2 << (32 - 22);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 64:
                {
                    // XorInstruction
                    value = ((value ^ 1262347216) - salt) ^ _secretKey[15];
                    return value;
                }
                case 65:
                {
                    // AddInstruction
                    value = ((value - 1780280992) ^ salt) - _secretKey[126];
                    return value;
                }
                case 66:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 13;
                    uint part1 = (uint)value << (32 - 13);
                    value = (int)(value2 | part1);
                    value ^= -1198162446 ^ salt;
                    value = (value - _secretKey[85]) * 1314512283;
                    return value;
                }
                case 67:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[128] - salt) * 463417823;
                    return value;
                }
                case 68:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[178]);
                    uint part1 = value2 >> 24;
                    uint part2 = value2 << (32 - 24);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 69:
                {
                    // XorInstruction
                    value = ((value ^ 1649427052) - salt) ^ _secretKey[61];
                    return value;
                }
                case 70:
                {
                    // MultipleRotateXorInstruction
                    value ^= 849172121 ^ salt;
                    uint value2 = (uint)value >> 17;
                    uint part1 = (uint)value << (32 - 17);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[83]) * 368180765;
                    return value;
                }
                case 71:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[169]);
                    uint part1 = value2 >> 16;
                    uint part2 = value2 << (32 - 16);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 72:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 20;
                    uint part1 = (uint)value << (32 - 20);
                    value = (int)(value2 | part1);
                    value -= -2092062916 + _secretKey[138];
                    value ^= 1068287172 ^ salt;
                    return value;
                }
                case 73:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[34] - salt) * -495145181;
                    return value;
                }
                case 74:
                {
                    // MultipleRotateXorInstruction
                    value ^= -145743337 ^ salt;
                    uint value2 = (uint)value >> 29;
                    uint part1 = (uint)value << (32 - 29);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[30]) * 1735064809;
                    return value;
                }
                case 75:
                {
                    // MultipleRotateXorInstruction
                    value ^= 280941267 ^ salt;
                    uint value2 = (uint)value >> 4;
                    uint part1 = (uint)value << (32 - 4);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[142]) * 442035963;
                    return value;
                }
                case 76:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[156] - salt) * -971441783;
                    return value;
                }
                case 77:
                {
                    // AddRotateXorInstruction
                    value ^= 827331935 ^ salt;
                    uint value2 = (uint)value >> 7;
                    uint part1 = (uint)value << (32 - 7);
                    value = (int)(value2 | part1);
                    value -= 314625916 + _secretKey[192];
                    return value;
                }
                case 78:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[141] - salt) * -1649657957;
                    return value;
                }
                case 79:
                {
                    // AddXorRotateInstruction
                    uint part1 = (uint)value >> 11;
                    uint part2 = (uint)value << (32 - 11);
                    value = (int)(part1 | part2);
                    value ^= -11549173 ^ salt;
                    value -= 1607953190 + _secretKey[133];
                    return value;
                }
                case 80:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 25;
                    uint part1 = (uint)value << (32 - 25);
                    value = (int)(value2 | part1);
                    value -= 687186546 + _secretKey[95];
                    value ^= -1454482890 ^ salt;
                    return value;
                }
                case 81:
                {
                    // XorInstruction
                    value = ((value ^ 814860713) - salt) ^ _secretKey[195];
                    return value;
                }
                case 82:
                {
                    // AddRotateXorInstruction
                    value ^= 213310246 ^ salt;
                    uint value2 = (uint)value >> 19;
                    uint part1 = (uint)value << (32 - 19);
                    value = (int)(value2 | part1);
                    value -= 1998643542 + _secretKey[171];
                    return value;
                }
                case 83:
                {
                    // AddRotateXorInstruction
                    value ^= -696314173 ^ salt;
                    uint value2 = (uint)value >> 14;
                    uint part1 = (uint)value << (32 - 14);
                    value = (int)(value2 | part1);
                    value -= 542686146 + _secretKey[249];
                    return value;
                }
                case 84:
                {
                    // AddRotateXorInstruction
                    value ^= 118718247 ^ salt;
                    uint value2 = (uint)value >> 9;
                    uint part1 = (uint)value << (32 - 9);
                    value = (int)(value2 | part1);
                    value -= 1734820207 + _secretKey[2];
                    return value;
                }
                case 85:
                {
                    // XorInstruction
                    value = ((value ^ 1553710234) - salt) ^ _secretKey[143];
                    return value;
                }
                case 86:
                {
                    // AddRotateXorInstruction
                    value ^= -1402843691 ^ salt;
                    uint value2 = (uint)value >> 5;
                    uint part1 = (uint)value << (32 - 5);
                    value = (int)(value2 | part1);
                    value -= -217984331 + _secretKey[146];
                    return value;
                }
                case 87:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[5] - salt) * -814971689;
                    return value;
                }
                case 88:
                {
                    // MultipleRotateXorInstruction
                    value ^= -2044505542 ^ salt;
                    uint value2 = (uint)value >> 28;
                    uint part1 = (uint)value << (32 - 28);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[158]) * 681320217;
                    return value;
                }
                case 89:
                {
                    // AddInstruction
                    value = ((value - -1213654475) ^ salt) - _secretKey[40];
                    return value;
                }
                case 90:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 6;
                    uint part1 = (uint)value << (32 - 6);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[206]) * 583163349;
                    value ^= -1886972278 ^ salt;
                    return value;
                }
                case 91:
                {
                    // AddRotateXorInstruction
                    value ^= -979249928 ^ salt;
                    uint value2 = (uint)value >> 23;
                    uint part1 = (uint)value << (32 - 23);
                    value = (int)(value2 | part1);
                    value -= -1724625239 + _secretKey[223];
                    return value;
                }
                case 92:
                {
                    // XorInstruction
                    value = ((value ^ -1104541704) - salt) ^ _secretKey[83];
                    return value;
                }
                case 93:
                {
                    // XorInstruction
                    value = ((value ^ 311150152) - salt) ^ _secretKey[31];
                    return value;
                }
                case 94:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 17;
                    uint part1 = (uint)value << (32 - 17);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[176]) * 1535026385;
                    value ^= 116496631 ^ salt;
                    return value;
                }
                case 95:
                {
                    // MultipleRotateXorInstruction
                    value ^= 2133438141 ^ salt;
                    uint value2 = (uint)value >> 2;
                    uint part1 = (uint)value << (32 - 2);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[87]) * 1779203413;
                    return value;
                }
                case 96:
                {
                    // MultipleRotateXorInstruction
                    value ^= 225535005 ^ salt;
                    uint value2 = (uint)value >> 16;
                    uint part1 = (uint)value << (32 - 16);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[174]) * 521638757;
                    return value;
                }
                case 97:
                {
                    // MultipleRotateXorInstruction
                    value ^= -1703839105 ^ salt;
                    uint value2 = (uint)value >> 1;
                    uint part1 = (uint)value << (32 - 1);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[175]) * -1131776573;
                    return value;
                }
                case 98:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 15;
                    uint part1 = (uint)value << (32 - 15);
                    value = (int)(value2 | part1);
                    value -= -1783079937 + _secretKey[78];
                    value ^= -447564571 ^ salt;
                    return value;
                }
                case 99:
                {
                    // XorInstruction
                    value = ((value ^ -316631669) - salt) ^ _secretKey[111];
                    return value;
                }
                case 100:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 24;
                    uint part1 = (uint)value << (32 - 24);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[252]) * 898292471;
                    value ^= -405694625 ^ salt;
                    return value;
                }
                case 101:
                {
                    // MultipleXorRotateInstruction
                    uint value2 = (uint)value >> 6;
                    uint part1 = (uint)value << (32 - 6);
                    value = (int)(value2 | part1);
                    value ^= -1551058348 ^ salt;
                    value = (value - _secretKey[212]) * -22167815;
                    return value;
                }
                case 102:
                {
                    // AddInstruction
                    value = ((value - -853736135) ^ salt) - _secretKey[18];
                    return value;
                }
                case 103:
                {
                    // AddInstruction
                    value = ((value - 1321376878) ^ salt) - _secretKey[116];
                    return value;
                }
                case 104:
                {
                    // MultipleRotateXorInstruction
                    value ^= 541697309 ^ salt;
                    uint value2 = (uint)value >> 0;
                    uint part1 = (uint)value << (32 - 0);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[7]) * -1964889845;
                    return value;
                }
                case 105:
                {
                    // AddRotateXorInstruction
                    value ^= 1176608900 ^ salt;
                    uint value2 = (uint)value >> 4;
                    uint part1 = (uint)value << (32 - 4);
                    value = (int)(value2 | part1);
                    value -= -822594180 + _secretKey[1];
                    return value;
                }
                case 106:
                {
                    // AddInstruction
                    value = ((value - -882893600) ^ salt) - _secretKey[110];
                    return value;
                }
                case 107:
                {
                    // MultipleRotateXorInstruction
                    value ^= -1566546809 ^ salt;
                    uint value2 = (uint)value >> 23;
                    uint part1 = (uint)value << (32 - 23);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[114]) * 406480373;
                    return value;
                }
                case 108:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[97] - salt) * 200608377;
                    return value;
                }
                case 109:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 7;
                    uint part1 = (uint)value << (32 - 7);
                    value = (int)(value2 | part1);
                    value -= 1161425930 + _secretKey[43];
                    value ^= -72794161 ^ salt;
                    return value;
                }
                case 110:
                {
                    // AddInstruction
                    value = ((value - -1619543125) ^ salt) - _secretKey[238];
                    return value;
                }
                case 111:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 12;
                    uint part1 = (uint)value << (32 - 12);
                    value = (int)(value2 | part1);
                    value -= -1766468683 + _secretKey[241];
                    value ^= 1170459122 ^ salt;
                    return value;
                }
                case 112:
                {
                    // AddXorRotateInstruction
                    uint part1 = (uint)value >> 11;
                    uint part2 = (uint)value << (32 - 11);
                    value = (int)(part1 | part2);
                    value ^= 323019346 ^ salt;
                    value -= 251687012 + _secretKey[219];
                    return value;
                }
                case 113:
                {
                    // AddInstruction
                    value = ((value - -1049972438) ^ salt) - _secretKey[97];
                    return value;
                }
                case 114:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 10;
                    uint part1 = (uint)value << (32 - 10);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[216]) * 594045631;
                    value ^= -492239002 ^ salt;
                    return value;
                }
                case 115:
                {
                    // AddInstruction
                    value = ((value - -748126329) ^ salt) - _secretKey[221];
                    return value;
                }
                case 116:
                {
                    // AddXorRotateInstruction
                    uint part1 = (uint)value >> 17;
                    uint part2 = (uint)value << (32 - 17);
                    value = (int)(part1 | part2);
                    value ^= -5933889 ^ salt;
                    value -= -441051263 + _secretKey[96];
                    return value;
                }
                case 117:
                {
                    // MultipleRotateXorInstruction
                    value ^= 543895274 ^ salt;
                    uint value2 = (uint)value >> 11;
                    uint part1 = (uint)value << (32 - 11);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[88]) * 1253478165;
                    return value;
                }
                case 118:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[140] - salt) * 1897067971;
                    return value;
                }
                case 119:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[175]);
                    uint part1 = value2 >> 18;
                    uint part2 = value2 << (32 - 18);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 120:
                {
                    // MultipleRotateXorInstruction
                    value ^= 1300544743 ^ salt;
                    uint value2 = (uint)value >> 16;
                    uint part1 = (uint)value << (32 - 16);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[57]) * -927555255;
                    return value;
                }
                case 121:
                {
                    // XorAddRotateInstruction
                    uint value2 = (uint)value >> 1;
                    uint part1 = (uint)value << (32 - 1);
                    value = (int)(value2 | part1);
                    value -= 678597707 + _secretKey[119];
                    value ^= -547380749 ^ salt;
                    return value;
                }
                case 122:
                {
                    // XorMultipleRotateInstruction
                    uint value2 = (uint)value >> 19;
                    uint part1 = (uint)value << (32 - 19);
                    value = (int)(value2 | part1);
                    value = (value - _secretKey[191]) * -1394333385;
                    value ^= 683601851 ^ salt;
                    return value;
                }
                case 123:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[15]);
                    uint part1 = value2 >> 20;
                    uint part2 = value2 << (32 - 20);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 124:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[132]);
                    uint part1 = value2 >> 8;
                    uint part2 = value2 << (32 - 8);
                    value = (int)(part1 | part2);
                    return value;
                }
                case 125:
                {
                    // MultipleInstruction
                    value = (value - _secretKey[120] - salt) * 412809175;
                    return value;
                }
                case 126:
                {
                    // AddInstruction
                    value = ((value - -1374139785) ^ salt) - _secretKey[197];
                    return value;
                }
                case 127:
                {
                    // BitRotateInstruction
                    uint value2 = (uint)((value - salt) ^ _secretKey[26]);
                    uint part1 = value2 >> 15;
                    uint part2 = value2 << (32 - 15);
                    value = (int)(part1 | part2);
                    return value;
                }

                default: throw new System.Exception($"Invalid opCode:{opCode}");
            }
        }

    }
}

