[[Screens]]
DisplayIndex = 0
Activate = true
X = 0
Y = 0
Width = 1920
Height = 1080
Topmost = false
Borderless = false

[[Screens]]
DisplayIndex = 1
Activate = true
X = 1920
Y = 0
Width = 1920
Height = 1080
Topmost = false
Borderless = false
